version: "3.8"

service:
  db:
    image: postgres
    env_file: ./envs/env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  migration:
    build: .
    env_file: ./envs/env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate'

    std_in: true
    tty: true

    depends_on:
      - db
  
  kmdb:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - 8000:8000
    depends_on:
      - db
      - migration

volumes:
    postgres_data:
      external: true