version: "3.8"

service:
  db:
    image: postgres
    enviroment: ./envs/env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  migration:
    build: .
    env
  
  kmdb:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - 8000:8000
    depends_on:
      - db

volumes:
    postgres_data: