# Generated by Django 3.2.7 on 2021-09-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210929_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
    ]
