# Generated by Django 3.2.7 on 2021-10-01 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='{"stars": ["Ensure this value is greater than or equal to 1."]}'), django.core.validators.MaxValueValidator(10, message='{"stars": ["Ensure this value is less than or equal to 10."]}')]),
        ),
    ]
